
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using Flight_DAL;
using System.Collections.Specialized;
using System.Data.SqlClient;
using System.Data;
namespace Flight_BLL
{
	public class FromVersion : _FromVersion
	{
		public FromVersion()
		{
		
		}

        public bool GetVersionsByFormID(int FormID, string filterText)
        {
            ListDictionary parameters = new ListDictionary();

            parameters.Add(new SqlParameter("@FormID", SqlDbType.Int, 0), FormID);
            parameters.Add(new SqlParameter("@filterText", SqlDbType.NVarChar, 50), filterText);

            return LoadFromSql("GetVersionsByFormID", parameters);
            
        }
    }
}
