
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using Flight_DAL;
using System.Collections.Specialized;
using System.Data.SqlClient;
using System.Data;
namespace Flight_BLL
{
	public class Comment : _Comment
	{
		public Comment()
		{
		
		}

        public virtual bool GetIssuesComments(int IssueID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@IssueID", SqlDbType.Int, 0), IssueID);
            return LoadFromSql("GetIssuesComments", parameters);
        }
	}
}
