
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using Flight_DAL;
using System.Collections.Specialized;
using System.Data.SqlClient;
using System.Data;
namespace Flight_BLL
{
	public class Issue : _Issue
	{
		public Issue()
		{
		
		}

        public virtual bool GetAllIssuesByUserID(Guid? userID, string filterText, int TypeID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@userID", SqlDbType.UniqueIdentifier, 0), userID.Value);
            parameters.Add(new SqlParameter("@filterText", SqlDbType.NVarChar, 100), filterText);
            parameters.Add(new SqlParameter("@TypeID", SqlDbType.Int, 0), TypeID);
            return LoadFromSql("GetAllIssuesByUserID", parameters);
        }

        public virtual bool GetAllIssues(string filterText, int TypeID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@filterText", SqlDbType.NVarChar, 100), filterText);
            parameters.Add(new SqlParameter("@TypeID", SqlDbType.Int, 0), TypeID);
            return LoadFromSql("GetAllIssues", parameters);
        }
	}
}
