
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using Flight_DAL;
using System.Collections.Specialized;
using System.Data.SqlClient;
using System.Data;
namespace Flight_BLL
{
	public class ManualVersion : _ManualVersion
	{
		public ManualVersion()
		{
		
		}

        public bool GetVersionsByManualID(int ManualID, string filterText)
        {
            ListDictionary parameters = new ListDictionary();

            parameters.Add(new SqlParameter("@ManualID", SqlDbType.Int, 0), ManualID);
            parameters.Add(new SqlParameter("@filterText", SqlDbType.NVarChar, 50), filterText);

            return LoadFromSql("GetVersionsByManualID", parameters);
        }
	}
}
