
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using Flight_DAL;
using System.Collections.Specialized;
using System.Data.SqlClient;
using System.Data;
namespace Flight_BLL
{
	public class Schedule : _Schedule
	{
		public Schedule()
		{
		
		}

        public bool GetAllSchedules(string query, DateTime dateFrom, DateTime dateTo)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@query", SqlDbType.NVarChar, 50), query);
            parameters.Add(new SqlParameter("@FromDate", SqlDbType.DateTime, 0), dateFrom);
            parameters.Add(new SqlParameter("@ToDate", SqlDbType.DateTime, 0), dateTo);
            return LoadFromSql("GetAllSchedules", parameters);
        }
        public virtual bool GetSchedulesByUserID(Guid UserID, string query, DateTime dateFrom, DateTime dateTo)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@UserID", SqlDbType.UniqueIdentifier, 0), UserID);
            parameters.Add(new SqlParameter("@query", SqlDbType.NVarChar, 50), query);
            parameters.Add(new SqlParameter("@FromDate", SqlDbType.DateTime, 0), dateFrom);
            parameters.Add(new SqlParameter("@ToDate", SqlDbType.DateTime, 0), dateTo);
            return LoadFromSql("GetSchedulesByUserID", parameters);
        }
	}
}
