
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using Pricing.DAL;// We should use the namespace of Data access layer generated form business entity

namespace Pricing.BLL
{
	public class PricingStatus : _PricingStatus
	{
		public PricingStatus()
		{
		
		}

        public bool GetStatusByParentID(int PID)
        {
            return LoadFromRawSql(@"Select PS.* from PricingStatus PS 
                                    inner join StatusHierarchy SH on PS.PricingStatusID = SH.StatusID 
                                    where SH.ParentStatusID = {0}", PID);
        }
	}
}
