
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace Flight_DAL
{
	public abstract class _IssueAttachment : SqlClientEntity
	{
		public _IssueAttachment()
		{
			this.QuerySource = "IssueAttachment";
			this.MappingName = "IssueAttachment";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_IssueAttachmentLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int IssueAttachmentID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.IssueAttachmentID, IssueAttachmentID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_IssueAttachmentLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter IssueAttachmentID
			{
				get
				{
					return new SqlParameter("@IssueAttachmentID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter IssueID
			{
				get
				{
					return new SqlParameter("@IssueID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter AttachmentID
			{
				get
				{
					return new SqlParameter("@AttachmentID", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string IssueAttachmentID = "IssueAttachmentID";
            public const string IssueID = "IssueID";
            public const string AttachmentID = "AttachmentID";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[IssueAttachmentID] = _IssueAttachment.PropertyNames.IssueAttachmentID;
					ht[IssueID] = _IssueAttachment.PropertyNames.IssueID;
					ht[AttachmentID] = _IssueAttachment.PropertyNames.AttachmentID;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string IssueAttachmentID = "IssueAttachmentID";
            public const string IssueID = "IssueID";
            public const string AttachmentID = "AttachmentID";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[IssueAttachmentID] = _IssueAttachment.ColumnNames.IssueAttachmentID;
					ht[IssueID] = _IssueAttachment.ColumnNames.IssueID;
					ht[AttachmentID] = _IssueAttachment.ColumnNames.AttachmentID;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string IssueAttachmentID = "s_IssueAttachmentID";
            public const string IssueID = "s_IssueID";
            public const string AttachmentID = "s_AttachmentID";

		}
		#endregion		
		
		#region Properties
	
		public virtual int IssueAttachmentID
	    {
			get
	        {
				return base.Getint(ColumnNames.IssueAttachmentID);
			}
			set
	        {
				base.Setint(ColumnNames.IssueAttachmentID, value);
			}
		}

		public virtual int IssueID
	    {
			get
	        {
				return base.Getint(ColumnNames.IssueID);
			}
			set
	        {
				base.Setint(ColumnNames.IssueID, value);
			}
		}

		public virtual int AttachmentID
	    {
			get
	        {
				return base.Getint(ColumnNames.AttachmentID);
			}
			set
	        {
				base.Setint(ColumnNames.AttachmentID, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_IssueAttachmentID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IssueAttachmentID) ? string.Empty : base.GetintAsString(ColumnNames.IssueAttachmentID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IssueAttachmentID);
				else
					this.IssueAttachmentID = base.SetintAsString(ColumnNames.IssueAttachmentID, value);
			}
		}

		public virtual string s_IssueID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IssueID) ? string.Empty : base.GetintAsString(ColumnNames.IssueID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IssueID);
				else
					this.IssueID = base.SetintAsString(ColumnNames.IssueID, value);
			}
		}

		public virtual string s_AttachmentID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AttachmentID) ? string.Empty : base.GetintAsString(ColumnNames.AttachmentID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AttachmentID);
				else
					this.AttachmentID = base.SetintAsString(ColumnNames.AttachmentID, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter IssueAttachmentID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IssueAttachmentID, Parameters.IssueAttachmentID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IssueID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IssueID, Parameters.IssueID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AttachmentID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AttachmentID, Parameters.AttachmentID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter IssueAttachmentID
		    {
				get
		        {
					if(_IssueAttachmentID_W == null)
	        	    {
						_IssueAttachmentID_W = TearOff.IssueAttachmentID;
					}
					return _IssueAttachmentID_W;
				}
			}

			public WhereParameter IssueID
		    {
				get
		        {
					if(_IssueID_W == null)
	        	    {
						_IssueID_W = TearOff.IssueID;
					}
					return _IssueID_W;
				}
			}

			public WhereParameter AttachmentID
		    {
				get
		        {
					if(_AttachmentID_W == null)
	        	    {
						_AttachmentID_W = TearOff.AttachmentID;
					}
					return _AttachmentID_W;
				}
			}

			private WhereParameter _IssueAttachmentID_W = null;
			private WhereParameter _IssueID_W = null;
			private WhereParameter _AttachmentID_W = null;

			public void WhereClauseReset()
			{
				_IssueAttachmentID_W = null;
				_IssueID_W = null;
				_AttachmentID_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter IssueAttachmentID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IssueAttachmentID, Parameters.IssueAttachmentID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IssueID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IssueID, Parameters.IssueID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AttachmentID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AttachmentID, Parameters.AttachmentID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter IssueAttachmentID
		    {
				get
		        {
					if(_IssueAttachmentID_W == null)
	        	    {
						_IssueAttachmentID_W = TearOff.IssueAttachmentID;
					}
					return _IssueAttachmentID_W;
				}
			}

			public AggregateParameter IssueID
		    {
				get
		        {
					if(_IssueID_W == null)
	        	    {
						_IssueID_W = TearOff.IssueID;
					}
					return _IssueID_W;
				}
			}

			public AggregateParameter AttachmentID
		    {
				get
		        {
					if(_AttachmentID_W == null)
	        	    {
						_AttachmentID_W = TearOff.AttachmentID;
					}
					return _AttachmentID_W;
				}
			}

			private AggregateParameter _IssueAttachmentID_W = null;
			private AggregateParameter _IssueID_W = null;
			private AggregateParameter _AttachmentID_W = null;

			public void AggregateClauseReset()
			{
				_IssueAttachmentID_W = null;
				_IssueID_W = null;
				_AttachmentID_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_IssueAttachmentInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.IssueAttachmentID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_IssueAttachmentUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_IssueAttachmentDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.IssueAttachmentID);
			p.SourceColumn = ColumnNames.IssueAttachmentID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.IssueAttachmentID);
			p.SourceColumn = ColumnNames.IssueAttachmentID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IssueID);
			p.SourceColumn = ColumnNames.IssueID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AttachmentID);
			p.SourceColumn = ColumnNames.AttachmentID;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
