
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace Flight_DAL
{
	public abstract class _UserGroup : SqlClientEntity
	{
		public _UserGroup()
		{
			this.QuerySource = "UserGroup";
			this.MappingName = "UserGroup";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_UserGroupLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(Guid UserId, int GroupId)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.UserId, UserId);

parameters.Add(Parameters.GroupId, GroupId);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_UserGroupLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter UserId
			{
				get
				{
					return new SqlParameter("@UserId", SqlDbType.UniqueIdentifier, 0);
				}
			}
			
			public static SqlParameter GroupId
			{
				get
				{
					return new SqlParameter("@GroupId", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string UserId = "UserId";
            public const string GroupId = "GroupId";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[UserId] = _UserGroup.PropertyNames.UserId;
					ht[GroupId] = _UserGroup.PropertyNames.GroupId;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string UserId = "UserId";
            public const string GroupId = "GroupId";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[UserId] = _UserGroup.ColumnNames.UserId;
					ht[GroupId] = _UserGroup.ColumnNames.GroupId;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string UserId = "s_UserId";
            public const string GroupId = "s_GroupId";

		}
		#endregion		
		
		#region Properties
	
		public virtual Guid UserId
	    {
			get
	        {
				return base.GetGuid(ColumnNames.UserId);
			}
			set
	        {
				base.SetGuid(ColumnNames.UserId, value);
			}
		}

		public virtual int GroupId
	    {
			get
	        {
				return base.Getint(ColumnNames.GroupId);
			}
			set
	        {
				base.Setint(ColumnNames.GroupId, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_UserId
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.UserId) ? string.Empty : base.GetGuidAsString(ColumnNames.UserId);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.UserId);
				else
					this.UserId = base.SetGuidAsString(ColumnNames.UserId, value);
			}
		}

		public virtual string s_GroupId
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.GroupId) ? string.Empty : base.GetintAsString(ColumnNames.GroupId);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.GroupId);
				else
					this.GroupId = base.SetintAsString(ColumnNames.GroupId, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter UserId
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.UserId, Parameters.UserId);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter GroupId
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.GroupId, Parameters.GroupId);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter UserId
		    {
				get
		        {
					if(_UserId_W == null)
	        	    {
						_UserId_W = TearOff.UserId;
					}
					return _UserId_W;
				}
			}

			public WhereParameter GroupId
		    {
				get
		        {
					if(_GroupId_W == null)
	        	    {
						_GroupId_W = TearOff.GroupId;
					}
					return _GroupId_W;
				}
			}

			private WhereParameter _UserId_W = null;
			private WhereParameter _GroupId_W = null;

			public void WhereClauseReset()
			{
				_UserId_W = null;
				_GroupId_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter UserId
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.UserId, Parameters.UserId);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter GroupId
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.GroupId, Parameters.GroupId);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter UserId
		    {
				get
		        {
					if(_UserId_W == null)
	        	    {
						_UserId_W = TearOff.UserId;
					}
					return _UserId_W;
				}
			}

			public AggregateParameter GroupId
		    {
				get
		        {
					if(_GroupId_W == null)
	        	    {
						_GroupId_W = TearOff.GroupId;
					}
					return _GroupId_W;
				}
			}

			private AggregateParameter _UserId_W = null;
			private AggregateParameter _GroupId_W = null;

			public void AggregateClauseReset()
			{
				_UserId_W = null;
				_GroupId_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_UserGroupInsert]";
	
			CreateParameters(cmd);
			    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_UserGroupUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_UserGroupDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.UserId);
			p.SourceColumn = ColumnNames.UserId;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.GroupId);
			p.SourceColumn = ColumnNames.GroupId;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.UserId);
			p.SourceColumn = ColumnNames.UserId;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.GroupId);
			p.SourceColumn = ColumnNames.GroupId;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
