
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace Flight_DAL
{
	public abstract class _Issue : SqlClientEntity
	{
		public _Issue()
		{
			this.QuerySource = "Issue";
			this.MappingName = "Issue";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_IssueLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int IssueID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.IssueID, IssueID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_IssueLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter IssueID
			{
				get
				{
					return new SqlParameter("@IssueID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter UserID
			{
				get
				{
					return new SqlParameter("@UserID", SqlDbType.UniqueIdentifier, 0);
				}
			}
			
			public static SqlParameter IssueText
			{
				get
				{
					return new SqlParameter("@IssueText", SqlDbType.NVarChar, 1073741823);
				}
			}
			
			public static SqlParameter IssueTitle
			{
				get
				{
					return new SqlParameter("@IssueTitle", SqlDbType.NVarChar, 500);
				}
			}
			
			public static SqlParameter IssueDate
			{
				get
				{
					return new SqlParameter("@IssueDate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter StatusID
			{
				get
				{
					return new SqlParameter("@StatusID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter IssueTypeID
			{
				get
				{
					return new SqlParameter("@IssueTypeID", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string IssueID = "IssueID";
            public const string UserID = "UserID";
            public const string IssueText = "IssueText";
            public const string IssueTitle = "IssueTitle";
            public const string IssueDate = "IssueDate";
            public const string StatusID = "StatusID";
            public const string IssueTypeID = "IssueTypeID";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[IssueID] = _Issue.PropertyNames.IssueID;
					ht[UserID] = _Issue.PropertyNames.UserID;
					ht[IssueText] = _Issue.PropertyNames.IssueText;
					ht[IssueTitle] = _Issue.PropertyNames.IssueTitle;
					ht[IssueDate] = _Issue.PropertyNames.IssueDate;
					ht[StatusID] = _Issue.PropertyNames.StatusID;
					ht[IssueTypeID] = _Issue.PropertyNames.IssueTypeID;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string IssueID = "IssueID";
            public const string UserID = "UserID";
            public const string IssueText = "IssueText";
            public const string IssueTitle = "IssueTitle";
            public const string IssueDate = "IssueDate";
            public const string StatusID = "StatusID";
            public const string IssueTypeID = "IssueTypeID";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[IssueID] = _Issue.ColumnNames.IssueID;
					ht[UserID] = _Issue.ColumnNames.UserID;
					ht[IssueText] = _Issue.ColumnNames.IssueText;
					ht[IssueTitle] = _Issue.ColumnNames.IssueTitle;
					ht[IssueDate] = _Issue.ColumnNames.IssueDate;
					ht[StatusID] = _Issue.ColumnNames.StatusID;
					ht[IssueTypeID] = _Issue.ColumnNames.IssueTypeID;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string IssueID = "s_IssueID";
            public const string UserID = "s_UserID";
            public const string IssueText = "s_IssueText";
            public const string IssueTitle = "s_IssueTitle";
            public const string IssueDate = "s_IssueDate";
            public const string StatusID = "s_StatusID";
            public const string IssueTypeID = "s_IssueTypeID";

		}
		#endregion		
		
		#region Properties
	
		public virtual int IssueID
	    {
			get
	        {
				return base.Getint(ColumnNames.IssueID);
			}
			set
	        {
				base.Setint(ColumnNames.IssueID, value);
			}
		}

		public virtual Guid UserID
	    {
			get
	        {
				return base.GetGuid(ColumnNames.UserID);
			}
			set
	        {
				base.SetGuid(ColumnNames.UserID, value);
			}
		}

		public virtual string IssueText
	    {
			get
	        {
				return base.Getstring(ColumnNames.IssueText);
			}
			set
	        {
				base.Setstring(ColumnNames.IssueText, value);
			}
		}

		public virtual string IssueTitle
	    {
			get
	        {
				return base.Getstring(ColumnNames.IssueTitle);
			}
			set
	        {
				base.Setstring(ColumnNames.IssueTitle, value);
			}
		}

		public virtual DateTime IssueDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.IssueDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.IssueDate, value);
			}
		}

		public virtual int StatusID
	    {
			get
	        {
				return base.Getint(ColumnNames.StatusID);
			}
			set
	        {
				base.Setint(ColumnNames.StatusID, value);
			}
		}

		public virtual int IssueTypeID
	    {
			get
	        {
				return base.Getint(ColumnNames.IssueTypeID);
			}
			set
	        {
				base.Setint(ColumnNames.IssueTypeID, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_IssueID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IssueID) ? string.Empty : base.GetintAsString(ColumnNames.IssueID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IssueID);
				else
					this.IssueID = base.SetintAsString(ColumnNames.IssueID, value);
			}
		}

		public virtual string s_UserID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.UserID) ? string.Empty : base.GetGuidAsString(ColumnNames.UserID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.UserID);
				else
					this.UserID = base.SetGuidAsString(ColumnNames.UserID, value);
			}
		}

		public virtual string s_IssueText
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IssueText) ? string.Empty : base.GetstringAsString(ColumnNames.IssueText);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IssueText);
				else
					this.IssueText = base.SetstringAsString(ColumnNames.IssueText, value);
			}
		}

		public virtual string s_IssueTitle
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IssueTitle) ? string.Empty : base.GetstringAsString(ColumnNames.IssueTitle);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IssueTitle);
				else
					this.IssueTitle = base.SetstringAsString(ColumnNames.IssueTitle, value);
			}
		}

		public virtual string s_IssueDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IssueDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.IssueDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IssueDate);
				else
					this.IssueDate = base.SetDateTimeAsString(ColumnNames.IssueDate, value);
			}
		}

		public virtual string s_StatusID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.StatusID) ? string.Empty : base.GetintAsString(ColumnNames.StatusID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.StatusID);
				else
					this.StatusID = base.SetintAsString(ColumnNames.StatusID, value);
			}
		}

		public virtual string s_IssueTypeID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IssueTypeID) ? string.Empty : base.GetintAsString(ColumnNames.IssueTypeID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IssueTypeID);
				else
					this.IssueTypeID = base.SetintAsString(ColumnNames.IssueTypeID, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter IssueID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IssueID, Parameters.IssueID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter UserID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.UserID, Parameters.UserID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IssueText
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IssueText, Parameters.IssueText);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IssueTitle
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IssueTitle, Parameters.IssueTitle);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IssueDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IssueDate, Parameters.IssueDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter StatusID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.StatusID, Parameters.StatusID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IssueTypeID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IssueTypeID, Parameters.IssueTypeID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter IssueID
		    {
				get
		        {
					if(_IssueID_W == null)
	        	    {
						_IssueID_W = TearOff.IssueID;
					}
					return _IssueID_W;
				}
			}

			public WhereParameter UserID
		    {
				get
		        {
					if(_UserID_W == null)
	        	    {
						_UserID_W = TearOff.UserID;
					}
					return _UserID_W;
				}
			}

			public WhereParameter IssueText
		    {
				get
		        {
					if(_IssueText_W == null)
	        	    {
						_IssueText_W = TearOff.IssueText;
					}
					return _IssueText_W;
				}
			}

			public WhereParameter IssueTitle
		    {
				get
		        {
					if(_IssueTitle_W == null)
	        	    {
						_IssueTitle_W = TearOff.IssueTitle;
					}
					return _IssueTitle_W;
				}
			}

			public WhereParameter IssueDate
		    {
				get
		        {
					if(_IssueDate_W == null)
	        	    {
						_IssueDate_W = TearOff.IssueDate;
					}
					return _IssueDate_W;
				}
			}

			public WhereParameter StatusID
		    {
				get
		        {
					if(_StatusID_W == null)
	        	    {
						_StatusID_W = TearOff.StatusID;
					}
					return _StatusID_W;
				}
			}

			public WhereParameter IssueTypeID
		    {
				get
		        {
					if(_IssueTypeID_W == null)
	        	    {
						_IssueTypeID_W = TearOff.IssueTypeID;
					}
					return _IssueTypeID_W;
				}
			}

			private WhereParameter _IssueID_W = null;
			private WhereParameter _UserID_W = null;
			private WhereParameter _IssueText_W = null;
			private WhereParameter _IssueTitle_W = null;
			private WhereParameter _IssueDate_W = null;
			private WhereParameter _StatusID_W = null;
			private WhereParameter _IssueTypeID_W = null;

			public void WhereClauseReset()
			{
				_IssueID_W = null;
				_UserID_W = null;
				_IssueText_W = null;
				_IssueTitle_W = null;
				_IssueDate_W = null;
				_StatusID_W = null;
				_IssueTypeID_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter IssueID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IssueID, Parameters.IssueID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter UserID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.UserID, Parameters.UserID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IssueText
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IssueText, Parameters.IssueText);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IssueTitle
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IssueTitle, Parameters.IssueTitle);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IssueDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IssueDate, Parameters.IssueDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter StatusID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.StatusID, Parameters.StatusID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IssueTypeID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IssueTypeID, Parameters.IssueTypeID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter IssueID
		    {
				get
		        {
					if(_IssueID_W == null)
	        	    {
						_IssueID_W = TearOff.IssueID;
					}
					return _IssueID_W;
				}
			}

			public AggregateParameter UserID
		    {
				get
		        {
					if(_UserID_W == null)
	        	    {
						_UserID_W = TearOff.UserID;
					}
					return _UserID_W;
				}
			}

			public AggregateParameter IssueText
		    {
				get
		        {
					if(_IssueText_W == null)
	        	    {
						_IssueText_W = TearOff.IssueText;
					}
					return _IssueText_W;
				}
			}

			public AggregateParameter IssueTitle
		    {
				get
		        {
					if(_IssueTitle_W == null)
	        	    {
						_IssueTitle_W = TearOff.IssueTitle;
					}
					return _IssueTitle_W;
				}
			}

			public AggregateParameter IssueDate
		    {
				get
		        {
					if(_IssueDate_W == null)
	        	    {
						_IssueDate_W = TearOff.IssueDate;
					}
					return _IssueDate_W;
				}
			}

			public AggregateParameter StatusID
		    {
				get
		        {
					if(_StatusID_W == null)
	        	    {
						_StatusID_W = TearOff.StatusID;
					}
					return _StatusID_W;
				}
			}

			public AggregateParameter IssueTypeID
		    {
				get
		        {
					if(_IssueTypeID_W == null)
	        	    {
						_IssueTypeID_W = TearOff.IssueTypeID;
					}
					return _IssueTypeID_W;
				}
			}

			private AggregateParameter _IssueID_W = null;
			private AggregateParameter _UserID_W = null;
			private AggregateParameter _IssueText_W = null;
			private AggregateParameter _IssueTitle_W = null;
			private AggregateParameter _IssueDate_W = null;
			private AggregateParameter _StatusID_W = null;
			private AggregateParameter _IssueTypeID_W = null;

			public void AggregateClauseReset()
			{
				_IssueID_W = null;
				_UserID_W = null;
				_IssueText_W = null;
				_IssueTitle_W = null;
				_IssueDate_W = null;
				_StatusID_W = null;
				_IssueTypeID_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_IssueInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.IssueID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_IssueUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_IssueDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.IssueID);
			p.SourceColumn = ColumnNames.IssueID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.IssueID);
			p.SourceColumn = ColumnNames.IssueID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.UserID);
			p.SourceColumn = ColumnNames.UserID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IssueText);
			p.SourceColumn = ColumnNames.IssueText;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IssueTitle);
			p.SourceColumn = ColumnNames.IssueTitle;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IssueDate);
			p.SourceColumn = ColumnNames.IssueDate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.StatusID);
			p.SourceColumn = ColumnNames.StatusID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IssueTypeID);
			p.SourceColumn = ColumnNames.IssueTypeID;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
