
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using COMBO_DAL;

namespace COMBO_BLL
{
	public class ComboCommentReport : _ComboCommentReport
	{
		public ComboCommentReport()
		{
		
		}

        public bool getGeneralCommentReports()
        {
            return LoadFromRawSql(@"SELECT CC.CommentText CommentText, CC.ComboPostID PostID , CC.ComboCommentID CommentID, COUNT(CCR.ComboCommentReportID) ReportsCount
                                    FROM ComboComment CC JOIN ComboCommentReport CCR ON CCR.ComboCommentID = CC.ComboCommentID
                                    GROUP BY CommentText, CC.ComboCommentID, CC.CommentDate, CC.ComboPostID
                                    ORDER BY CC.CommentDate DESC");
        }

        public bool getCommentReportsByCommentID(int CommentID)
        {
            string query = string.Format(@"SELECT CU.UserName UserName , CCR.ReportDate , CCR.ReportText
                                           FROM ComboUser CU JOIN ComboCommentReport CCR ON CCR.ComboUserID = CU.ComboUserID
                                           WHERE CCR.ComboCommentID = {0}", CommentID);
            return LoadFromRawSql(query);
        }
	}
}
