
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using COMBO_DAL;

namespace COMBO_BLL
{
	public class ComboPost : _ComboPost
	{
		public ComboPost()
		{
		
		}

        public virtual bool GetUserPostByUserID(int userid)
        {
            return LoadFromRawSql(@"Select P.*, U.UserName, A.Path ProfilePic, S.IsPostsDownloadable, case when PV.ComboPostID is null then 'False' else 'True' end IsFavourite, case when PL.ComboPostID is null then 'False' else 'True' end IsLike,U.UserRankID from ComboPost P
                                    Inner Join ComboUser U on P.ComboUserID = U.ComboUserID and 
                                                              (U.IsDeactivated <> 1 or U.IsDeactivated is null)
                                    Left join Attachment A on U.ProfileImgID = A.AttachmentID
                                    Left join ComboUserSettings S on P.ComboUserID = S.ComboUserID 
                                    Left join ComboPostFav PV on P.ComboPostID = PV.ComboPostID and PV.ComboUserID = {0}
                                    Left join ComboPostLike PL on P.ComboPostID = PL.ComboPostID and PL.ComboUserID = {0}
                                    Where P.ComboUserID = {0} and 
                                    (P.IsDeleted <> 1 or P.IsDeleted is null)                                                                          
                                    order by P.PostDate Desc", userid);
        }
	}
}
