
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using COMBO_DAL;
namespace COMBO_BLL
{
	public class VerificationRequest : _VerificationRequest
	{
		public VerificationRequest()
		{
		
		}

        public virtual bool getNewRequests()
        {
            return LoadFromRawSql(@"SELECT CU.UserName, CU.DisplayName, CU.ComboUserID, CU.Email, VR.RequestTypeID , VR.VerificationRequestID, VR.RequestTypeID
                                    FROM ComboUser CU JOIN VerificationRequest VR ON CU.ComboUserID = VR.ComboUserID
                                    WHERE VR.IsAccepted is NULL");
        }
        public virtual bool getAcceptedRequests()
        {
            return LoadFromRawSql(@"SELECT CU.UserName, CU.DisplayName, CU.ComboUserID, CU.Email, VR.RequestTypeID , VR.VerificationRequestID, VR.RequestTypeID
                                    FROM ComboUser CU JOIN VerificationRequest VR ON CU.ComboUserID = VR.ComboUserID
                                    WHERE VR.IsAccepted = 1");
        }
        public virtual bool getRefusedRequests()
        {
            return LoadFromRawSql(@"SELECT CU.UserName, CU.DisplayName, CU.ComboUserID, CU.Email, VR.RequestTypeID , VR.VerificationRequestID, VR.RequestTypeID
                                    FROM ComboUser CU JOIN VerificationRequest VR ON CU.ComboUserID = VR.ComboUserID
                                    WHERE VR.IsAccepted = 0");
        }
	}
}
