
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using COMBO_DAL;

namespace COMBO_BLL
{
	public class ComboUser : _ComboUser
	{
		public ComboUser()
		{
		    
		}

        public bool getAllUsers()
        {
            return LoadFromRawSql("SELECT * FROM ComboUser JOIN UserRank ON ComboUser.UserRankID = UserRank.UserRankID ORDER BY UserName ASC");
        }

        public bool getUsersSearch(string query, int UserRankID)
        {
            string sql1 = string.Format(@"SELECT * FROM ComboUser JOIN UserRank ON ComboUser.UserRankID = UserRank.UserRankID WHERE (((UserName LIKE N'%{0}%') OR (DisplayName LIKE N'%{0}%') OR (Email LIKE N'%{0}%')) AND ComboUser.UserRankID = {1}) ORDER BY UserName ASC", query, UserRankID);
            string sql2 = string.Format(@"SELECT * FROM ComboUser JOIN UserRank ON ComboUser.UserRankID = UserRank.UserRankID WHERE ((UserName LIKE N'%{0}%') OR (DisplayName LIKE N'%{0}%') OR (Email LIKE N'%{0}%')) ORDER BY UserName ASC", query);

            if (UserRankID!=0)
                return LoadFromRawSql(sql1);
            else
                return LoadFromRawSql(sql2);
        }
	}
}
