
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using COMBO_DAL;
namespace COMBO_BLL
{
	public class ComboUserLog : _ComboUserLog
	{
		public ComboUserLog()
		{
		
		}

        public virtual bool getLatestChanges(int UserID)
        {
            return LoadFromRawSql(@"");
        }
	}
}
