
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using COMBO_DAL;

namespace COMBO_BLL
{
	public class NotificationUserSettings : _NotificationUserSettings
	{
		public NotificationUserSettings()
		{
		
		}
	}
}
