
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Collections.Specialized;
using System.Data;
using System.Data.SqlClient;
using DAL;
namespace BLL
{
    public class PurchaseOrder : _PurchaseOrder
    {
        public PurchaseOrder()
        {

        }
        public bool SearchPurchaseOrder(DateTime DateFrom, DateTime DateTo, 
            DateTime DeliveryDateFrom, DateTime DeliveryDateTo, int PurchaseOrderNumber)
        {
            ListDictionary parameters = new ListDictionary();


            parameters.Add(new SqlParameter("@PurFromDate", SqlDbType.DateTime, 0), DateFrom);
            parameters.Add(new SqlParameter("@PurToDate", SqlDbType.DateTime, 0), DateTo);
            parameters.Add(new SqlParameter("@PurDeliveryDateFrom", SqlDbType.DateTime, 0), DeliveryDateFrom);
            parameters.Add(new SqlParameter("@PurDeliveryDateTo", SqlDbType.DateTime, 0), DeliveryDateTo);
            parameters.Add(new SqlParameter("@PurNumber", SqlDbType.Int, 0), PurchaseOrderNumber);

            return LoadFromSql("PurchaseOrderSearch", parameters);
        }
    }
}
